// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DanLavine/willow/internal/willow/brokers/queues (interfaces: QueueConstructor)

// Package queuesfakes is a generated GoMock package.
package queuesfakes

import (
	reflect "reflect"

	servererrors "github.com/DanLavine/willow/internal/server_errors"
	queues "github.com/DanLavine/willow/internal/willow/brokers/queues"
	v1 "github.com/DanLavine/willow/pkg/models/api/willow/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueConstructor is a mock of QueueConstructor interface.
type MockQueueConstructor struct {
	ctrl     *gomock.Controller
	recorder *MockQueueConstructorMockRecorder
}

// MockQueueConstructorMockRecorder is the mock recorder for MockQueueConstructor.
type MockQueueConstructorMockRecorder struct {
	mock *MockQueueConstructor
}

// NewMockQueueConstructor creates a new mock instance.
func NewMockQueueConstructor(ctrl *gomock.Controller) *MockQueueConstructor {
	mock := &MockQueueConstructor{ctrl: ctrl}
	mock.recorder = &MockQueueConstructorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueConstructor) EXPECT() *MockQueueConstructorMockRecorder {
	return m.recorder
}

// NewQueue mocks base method.
func (m *MockQueueConstructor) NewQueue(arg0 *v1.Create) (queues.ManagedQueue, *servererrors.ApiError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewQueue", arg0)
	ret0, _ := ret[0].(queues.ManagedQueue)
	ret1, _ := ret[1].(*servererrors.ApiError)
	return ret0, ret1
}

// NewQueue indicates an expected call of NewQueue.
func (mr *MockQueueConstructorMockRecorder) NewQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewQueue", reflect.TypeOf((*MockQueueConstructor)(nil).NewQueue), arg0)
}
