FROM golang:1.19

WORKDIR /usr/src/app

# Cache the go mod layer for dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# copy the entire project into this repo
COPY . .
RUN go build -v -o /usr/local/bin/limiter cmd/limiter/main.go

EXPOSE 8082

# Default run command, but the locker service is still required end env vars need to be set
CMD ["limiter", "-limiter-insecure-http"]