FROM golang:1.19

WORKDIR /usr/src/app

# Cache the go mod layer for dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# copy the entire project into this repo
COPY . .
RUN go build -v -o /usr/local/bin/locker cmd/locker/main.go

EXPOSE 8083

CMD ["locker", "-limiter-insecure-http"]