// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DanLavine/willow/internal/willow/brokers/queue_channels/constructor (interfaces: QueueChannelsConstrutor)
//
// Generated by this command:
//
//	mockgen -destination=constructorfakes/queue_channel_constructor_mock.go -package=constructorfakes github.com/DanLavine/willow/internal/willow/brokers/queue_channels/constructor QueueChannelsConstrutor
//

// Package constructorfakes is a generated GoMock package.
package constructorfakes

import (
	reflect "reflect"

	constructor "github.com/DanLavine/willow/internal/willow/brokers/queue_channels/constructor"
	datatypes "github.com/DanLavine/willow/pkg/models/datatypes"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueChannelsConstrutor is a mock of QueueChannelsConstrutor interface.
type MockQueueChannelsConstrutor struct {
	ctrl     *gomock.Controller
	recorder *MockQueueChannelsConstrutorMockRecorder
}

// MockQueueChannelsConstrutorMockRecorder is the mock recorder for MockQueueChannelsConstrutor.
type MockQueueChannelsConstrutorMockRecorder struct {
	mock *MockQueueChannelsConstrutor
}

// NewMockQueueChannelsConstrutor creates a new mock instance.
func NewMockQueueChannelsConstrutor(ctrl *gomock.Controller) *MockQueueChannelsConstrutor {
	mock := &MockQueueChannelsConstrutor{ctrl: ctrl}
	mock.recorder = &MockQueueChannelsConstrutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueChannelsConstrutor) EXPECT() *MockQueueChannelsConstrutorMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockQueueChannelsConstrutor) New(arg0 func(), arg1 string, arg2 datatypes.KeyValues) constructor.QueueChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0, arg1, arg2)
	ret0, _ := ret[0].(constructor.QueueChannel)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockQueueChannelsConstrutorMockRecorder) New(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockQueueChannelsConstrutor)(nil).New), arg0, arg1, arg2)
}
